version = 0.1
[default]
[default.local_start_api]
environment_variables=[
  "DYNAMODB_TABLE=Credentials",
  "DYNAMODB_ENDPOINT_URL=http://host.docker.internal:8000",
  "REPOSITORY_TYPE=dynamodb",
  "AWS_ACCESS_KEY_ID=dummy",
  "AWS_SECRET_ACCESS_KEY=dummy",
  "AWS_DEFAULT_REGION=us-east-1",
  "AWS_SAM_LOCAL=true"
]
[default.deploy]
stack_name = "SAMCredentialApiStack"
confirm_changeset = false
fail_on_empty_changeset = false
environment_variables=[
  "AWS_SAM_LOCAL=false",
  "AWS_DEFAULT_REGION=us-east-1"
]
