AWSTemplateFormatVersion: '2010-09-01'
Transform: AWS::Serverless-2016-10-31

Resources:
  CredentialApi:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./app
      Handler: main.handler
      Runtime: python3.11
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY