Resources:
  CredentialApi:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: app/main.handler
      Runtime: python3.11
      Timeout: 15
      MemorySize: 256
      Environment:
        Variables:
          DYNAMODB_CREDENTIALS_TABLE: !Ref CredentialStatusTable
          DYNAMODB_API_KEYS_TABLE: !Ref ApiKeysTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CredentialStatusTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ApiKeysTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref ApiGatewayApi
            Auth:
              AuthorizationType: 'NONE'

  CredentialStatusTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Credentials"  # Set the table name to "Credentials"
      BillingMode: PROVISIONED  # Use provisioned throughput as per the script
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      AttributeDefinitions:
        - AttributeName: "PK"  # Partition key
          AttributeType: "S"  # String
        - AttributeName: "SK"  # Sort key
          AttributeType: "S"  # String
      KeySchema:
        - AttributeName: "PK"  # Partition key
          KeyType: "HASH"
        - AttributeName: "SK"  # Sort key
          KeyType: "RANGE"
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  ApiKeysTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "ApiKeys"  # Set the table name to "ApiKeys"
      BillingMode: PROVISIONED  # Use provisioned throughput as per the script
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      AttributeDefinitions:
        - AttributeName: "PK"  # Partition key
          AttributeType: "S"  # String
        - AttributeName: "SK"  # Sort key
          AttributeType: "S"  # String
      KeySchema:
        - AttributeName: "PK"  # Partition key
          KeyType: "HASH"
        - AttributeName: "SK"  # Sort key
          KeyType: "RANGE"
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST, PATCH'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/credentials"

  TableName:
    Description: "DynamoDB table name"
    Value: !Ref CredentialStatusTable

  ApiKeysTableName:
    Description: "ApiKeys DynamoDB table name"
    Value: !Ref ApiKeysTable
